# Generated by Django 5.0.6 on 2024-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_age_member_phone_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
