# Generated by Django 5.0.6 on 2024-05-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='MemberTable',
        ),
    ]
