# Generated by Django 5.0.6 on 2024-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_membertable_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertable',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
